version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: testdb_task
    ports:
      - "5432:5432"


  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"