version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: testdb_task
    ports:
      - "5430:5432"
    networks:
      - mynet


  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge